description: AI4COVID -> PCA | wiai-facility v2.0

model:
  name: classical
  type: binary
  classes:
    - non-cough
    - cough
  method:
    name: SVM
    params:
      kernel: 'rbf'
      probability: True
      random_state: 0

data:
  raw_waveform: false

  target_transform:
    name: classification
    params:
      classes:
        - cough

  signal_transform:

    train:
    - name: Resample
      params:
        orig_freq: 44100
        new_freq: 16000
    - name: FixedPad
      params:
        target_size: 8000
        accept_longer_than_target: true
    - name: MFCC
      params:
        sample_rate: 16000
        n_mfcc: 64
        log_mels: true
        melkwargs:
          n_mels: 128
    - name: Rescale
      params: {}
    - name: Ensemble
      params:
        transforms_cfg:
          - - name: 'PCA'
              params: {'n_components': 10, 'norm': True, 'norm_order': 1}
          - - name: 'AxisMean'
              params: {}
        combine: 'concat'

    val:
    - name: Resample
      params:
        orig_freq: 44100
        new_freq: 16000
    - name: FixedPad
      params:
        target_size: 8000
        accept_longer_than_target: true
    - name: MFCC
      params:
        sample_rate: 16000
        n_mfcc: 64
        log_mels: true
        melkwargs:
          n_mels: 128
    - name: Rescale
      params: {}
    - name: Ensemble
      params:
        transforms_cfg:
          - - name: 'PCA'
              params: {'n_components': 10, 'norm': True, 'norm_order': 1}
          - - name: 'AxisMean'
              params: {}
        combine: 'concat'

  dataset:
    name: classification_dataset
    config:
      - name: flusense
        version: segmented-v1.0
    params:
      train:
        fraction: 1.0
      val:
        fraction: 1.0

  sampler:
      train:
        name: classification
        params:
          mode: balanced
      val:
        name: default

  collate_fn:
    name: classification_collate
    params: {'zero_pad': False}
