description: spec input trial 

model:
    name: classification
    type: binary
    batch_size: 128
    epochs: 400
    optimizer:
      name: Adam
      args:
        lr: 0.00001
        weight_decay: 0.001
      scheduler:
        name: StepLR
        update: epoch
        params:
          step_size: 10
          gamma: 0.95
    loss:
      train:
        name: cross-entropy
        params:
          reduction: none
      val:
        name: cross-entropy
        params:
          reduction: none
    classes:
      - non-covid
      - covid
    save:
        period: 5
        monitor: specificity
        monitor_mode: max
    load:
        version: cough-detection/flusense/resnet18-coughnet-db-melspec
        epoch: 167
        load_best: False
        resume_optimizer: false
    eval:
      maximize_metric: specificity
      maximize_mode: val
      aggregate:
        train: {}
        val:
          method: median
          at: softmax
    subset_tracker:
      val: {}
      

network:
    name: neural_net
    params:
        config:
        - name: resnet18
          params:
            in_channels: 1
            pretrained: true
        - name: AdaptiveAvgPool2d
          params:
            output_size:
            - 1
            - 1
        - name: Flatten
          params: {}
        - name: Dropout
          params:
            p: 0.4
        - name: Linear
          params:
            in_features: 512
            out_features: 256
        - name: ReLU
          params: {}
        - name: Dropout
          params:
            p: 0.4
        - name: Linear
          params:
            in_features: 256
            out_features: 128
        - name: ReLU
          params: {}
        - name: Dropout
          params:
            p: 0.4
        - name: Linear
          params:
            in_features: 128
            out_features: 2

data:
  raw_waveform: false
  target_transform:
    name: classification
    params:
      classes:
        - covid

  signal_transform:
    train:
    - name: RandomCrop
      params:
        crop_size: 201
        pad_mode: zero
    - name: TimeMasking
      augmentation: true
      params:
          max_len: 50
          max_num: 2
    - name: FrequencyMasking
      augmentation: true
      params:
          max_len: 50
          max_num: 2
    - name: Rescale
      params:
        value: 100
    - name: Unsqueeze
      params: {}

    val:
    - name: FixedPad
      params:
        target_size: 201
    - name: Rescale
      params:
        value: 100
    - name: Unsqueeze
      params: {}

  dataset:
    name: classification_dataset
    config:
      - name: wiai-release-mini-spectrograms
        version: default
    params:
      train:
        raw_waveform: False
      val:
        as_frames: True
        frame_length: 2000
        min_length: 2000
        hop_length: 500
        raw_waveform: False
  sampler:
    train:
        name: classification
        params:
            mode: default
    val:
        name: default
  collate_fn:
    name: classification_collate
    params: {}
