description: Overparameterized CNN with default stonybrook version with STFT transform

model:
    name: classification
    type: binary
    batch_size: 16
    epochs: 100
    optimizer:
      name: SGD
      args:
        lr: 0.001
        momentum: 0.9
        nesterov: true
      scheduler:
        update: epoch
        value: loss
        name: ReduceLROnPlateau
        params:
            mode: 'min'
            factor: 0.1
            patience: 5
            verbose: true
            threshold: 0.0001
            threshold_mode: abs
        lr: 0.0001
    classes:
      - non-cough
      - cough
    save:
        period: 2
        monitor: precision
        monitor_mode: max
    load:
        version: null
        epoch: -1
        load_best: False
        resume_optimizer: False

    name: neural_net
    params:
        config:
        - Conv2d:
            in_channels: 1
            out_channels: 64
            padding:
            - 3
            - 1
            kernel_size:
            - 7
            - 3
        - BatchNorm2d:
            num_features: 64
        - ReLU: {}
        - Conv2d:
            in_channels: 64
            out_channels: 64
            padding:
            - 3
            - 1
            kernel_size:
            - 7
            - 3
        - BatchNorm2d:
            num_features: 64
        - ReLU: {}
        - Conv2d:
            in_channels: 64
            out_channels: 64
            padding:
            - 3
            - 1
            kernel_size:
            - 7
            - 3
        - BatchNorm2d:
            num_features: 64
        - ReLU: {}
        - MaxPool2d:
            kernel_size: 2
        - Conv2d:
            in_channels: 64
            out_channels: 128
            padding:
            - 3
            - 1
            kernel_size:
            - 7
            - 3
        - BatchNorm2d:
            num_features: 128
        - ReLU: {}
        - Conv2d:
            in_channels: 128
            out_channels: 128
            padding:
            - 3
            - 1
            kernel_size:
            - 7
            - 3
        - BatchNorm2d:
            num_features: 128
        - ReLU: {}
        - Conv2d:
            in_channels: 128
            out_channels: 128
            padding:
            - 3
            - 1
            kernel_size:
            - 7
            - 3
        - BatchNorm2d:
            num_features: 128
        - ReLU: {}
        - MaxPool2d:
            kernel_size: 2
        - Conv2d:
            in_channels: 128
            out_channels: 256
            padding:
            - 3
            - 1
            kernel_size:
            - 7
            - 3
        - BatchNorm2d:
            num_features: 256
        - ReLU: {}
        - Conv2d:
            in_channels: 256
            out_channels: 256
            padding:
            - 3
            - 1
            kernel_size:
            - 7
            - 3
        - BatchNorm2d:
            num_features: 256
        - ReLU: {}
        - Conv2d:
            in_channels: 256
            out_channels: 256
            padding:
            - 3
            - 1
            kernel_size:
            - 7
            - 3
        - BatchNorm2d:
            num_features: 256
        - ReLU: {}
        - MaxPool2d:
            kernel_size: 2
        - Conv2d:
            in_channels: 256
            out_channels: 512
            padding:
            - 3
            - 1
            kernel_size:
            - 7
            - 3
        - BatchNorm2d:
            num_features: 512
        - ReLU: {}
        - Conv2d:
            in_channels: 512
            out_channels: 512
            padding:
            - 3
            - 1
            kernel_size:
            - 7
            - 3
        - BatchNorm2d:
            num_features: 512
        - ReLU: {}
        - Conv2d:
            in_channels: 512
            out_channels: 512
            padding:
            - 3
            - 1
            kernel_size:
            - 7
            - 3
        - BatchNorm2d:
            num_features: 512
        - ReLU: {}
        - AdaptiveAvgPool2d:
            output_size:
            - 1
            - 1
        - Flatten: {}
        - Linear:
            in_features: 512
            out_features: 256
        - ReLU: {}
        - Linear:
            in_features: 256
            out_features: 128
        - ReLU: {}
        - Linear:
            in_features: 128
            out_features: 2

data:
  raw_waveform: false
  target_transform:
    name: classification
    params:
      classes:
        - cough
  signal_transform:
    train:
    - name: Resample
      params:
        orig_freq: 44100
        new_freq: 16000
    - name: STFT
      params:
        n_fft: 512
        window: hann
    - name: Resize
      params:
        size:
          - 257
          - 20
    - name: Rescale
      params: {}
    val:
    - name: Resample
      params:
        orig_freq: 44100
        new_freq: 16000
    - name: STFT
      params:
        n_fft: 512
        window: hann
    - name: Resize
      params:
        size:
          - 257
          - 20
    - name: Rescale
      params: {}
  dataset:
    name: classification_dataset
    config:
      - name: flusense
        version: segmented-v1.0
    params:
      train:
        fraction: 0.1
      val:
        fraction: 0.1
  collate_fn:
    name: classification_collate
    params: {}

